package ui;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class Play {
  private JPanel PlayPanel;
  private JButton button1;
  private JButton button2;
  private JButton button3;
  private JButton button4;
  private JButton button5;
  private JButton button6;
  private JButton button7;
  private JButton button8;
  private JButton button9;
  private JButton button10;
  private JButton button11;
  private JButton button12;
  private JButton button13;
  private JButton button14;
  private JButton button15;
  private JButton button16;
  private JButton button17;
  private JButton button18;
  private JButton button19;
  private JButton button20;
  private JButton button21;
  private JButton button22;
  private JButton button23;
  private JButton button24;
  private JButton button25;
  private JTextField textField1;
  private JTextField textField2;
  private JButton submitButton;

  public JPanel getPlayPanel() {
    return PlayPanel;
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    PlayPanel = new JPanel();
    PlayPanel.setLayout(new GridBagLayout());
    PlayPanel.setMinimumSize(new Dimension(800, 450));
    button1 = new JButton();
    button1.setMaximumSize(new Dimension(150, 80));
    button1.setMinimumSize(new Dimension(150, 60));
    button1.setPreferredSize(new Dimension(150, 60));
    button1.setSelected(false);
    button1.setText("Button");
    button1.setVisible(true);
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button1, gbc);
    button2 = new JButton();
    button2.setMaximumSize(new Dimension(150, 80));
    button2.setMinimumSize(new Dimension(150, 60));
    button2.setPreferredSize(new Dimension(150, 60));
    button2.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button2, gbc);
    button3 = new JButton();
    button3.setMaximumSize(new Dimension(150, 80));
    button3.setMinimumSize(new Dimension(150, 60));
    button3.setPreferredSize(new Dimension(150, 60));
    button3.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button3, gbc);
    button4 = new JButton();
    button4.setMaximumSize(new Dimension(150, 80));
    button4.setMinimumSize(new Dimension(150, 60));
    button4.setPreferredSize(new Dimension(150, 60));
    button4.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 1;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button4, gbc);
    button5 = new JButton();
    button5.setMaximumSize(new Dimension(150, 80));
    button5.setMinimumSize(new Dimension(150, 60));
    button5.setPreferredSize(new Dimension(150, 60));
    button5.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 5;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button5, gbc);
    button6 = new JButton();
    button6.setMaximumSize(new Dimension(150, 80));
    button6.setMinimumSize(new Dimension(150, 60));
    button6.setPreferredSize(new Dimension(150, 60));
    button6.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button6, gbc);
    button7 = new JButton();
    button7.setMaximumSize(new Dimension(150, 80));
    button7.setMinimumSize(new Dimension(150, 60));
    button7.setPreferredSize(new Dimension(150, 60));
    button7.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button7, gbc);
    button8 = new JButton();
    button8.setMaximumSize(new Dimension(150, 80));
    button8.setMinimumSize(new Dimension(150, 60));
    button8.setPreferredSize(new Dimension(150, 60));
    button8.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button8, gbc);
    button9 = new JButton();
    button9.setMaximumSize(new Dimension(150, 80));
    button9.setMinimumSize(new Dimension(150, 60));
    button9.setPreferredSize(new Dimension(150, 60));
    button9.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 2;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button9, gbc);
    button10 = new JButton();
    button10.setMaximumSize(new Dimension(150, 80));
    button10.setMinimumSize(new Dimension(150, 60));
    button10.setPreferredSize(new Dimension(150, 60));
    button10.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 5;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button10, gbc);
    button11 = new JButton();
    button11.setMaximumSize(new Dimension(150, 80));
    button11.setMinimumSize(new Dimension(150, 60));
    button11.setPreferredSize(new Dimension(150, 60));
    button11.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button11, gbc);
    button12 = new JButton();
    button12.setMaximumSize(new Dimension(150, 80));
    button12.setMinimumSize(new Dimension(150, 60));
    button12.setPreferredSize(new Dimension(150, 60));
    button12.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button12, gbc);
    button13 = new JButton();
    button13.setMaximumSize(new Dimension(150, 80));
    button13.setMinimumSize(new Dimension(150, 60));
    button13.setPreferredSize(new Dimension(150, 60));
    button13.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button13, gbc);
    button14 = new JButton();
    button14.setMaximumSize(new Dimension(150, 80));
    button14.setMinimumSize(new Dimension(150, 60));
    button14.setPreferredSize(new Dimension(150, 60));
    button14.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 3;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button14, gbc);
    button15 = new JButton();
    button15.setMaximumSize(new Dimension(150, 80));
    button15.setMinimumSize(new Dimension(150, 60));
    button15.setPreferredSize(new Dimension(150, 60));
    button15.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 5;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button15, gbc);
    button16 = new JButton();
    button16.setMaximumSize(new Dimension(150, 80));
    button16.setMinimumSize(new Dimension(150, 60));
    button16.setPreferredSize(new Dimension(150, 60));
    button16.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 4;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button16, gbc);
    button17 = new JButton();
    button17.setMaximumSize(new Dimension(150, 80));
    button17.setMinimumSize(new Dimension(150, 60));
    button17.setPreferredSize(new Dimension(150, 60));
    button17.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 4;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button17, gbc);
    button18 = new JButton();
    button18.setMaximumSize(new Dimension(150, 80));
    button18.setMinimumSize(new Dimension(150, 60));
    button18.setPreferredSize(new Dimension(150, 60));
    button18.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 4;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button18, gbc);
    button19 = new JButton();
    button19.setMaximumSize(new Dimension(150, 80));
    button19.setMinimumSize(new Dimension(150, 60));
    button19.setPreferredSize(new Dimension(150, 60));
    button19.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 4;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button19, gbc);
    button20 = new JButton();
    button20.setMaximumSize(new Dimension(150, 80));
    button20.setMinimumSize(new Dimension(150, 60));
    button20.setPreferredSize(new Dimension(150, 60));
    button20.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 5;
    gbc.gridy = 4;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button20, gbc);
    button21 = new JButton();
    button21.setMaximumSize(new Dimension(150, 80));
    button21.setMinimumSize(new Dimension(150, 60));
    button21.setPreferredSize(new Dimension(150, 60));
    button21.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 5;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button21, gbc);
    button22 = new JButton();
    button22.setMaximumSize(new Dimension(150, 80));
    button22.setMinimumSize(new Dimension(150, 60));
    button22.setPreferredSize(new Dimension(150, 60));
    button22.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 5;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button22, gbc);
    button23 = new JButton();
    button23.setMaximumSize(new Dimension(150, 80));
    button23.setMinimumSize(new Dimension(150, 60));
    button23.setPreferredSize(new Dimension(150, 60));
    button23.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 5;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button23, gbc);
    button24 = new JButton();
    button24.setMaximumSize(new Dimension(150, 80));
    button24.setMinimumSize(new Dimension(150, 60));
    button24.setPreferredSize(new Dimension(150, 60));
    button24.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 5;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button24, gbc);
    button25 = new JButton();
    button25.setMaximumSize(new Dimension(150, 80));
    button25.setMinimumSize(new Dimension(150, 60));
    button25.setPreferredSize(new Dimension(150, 60));
    button25.setText("Button");
    gbc = new GridBagConstraints();
    gbc.gridx = 5;
    gbc.gridy = 5;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    PlayPanel.add(button25, gbc);
    final JLabel label1 = new JLabel();
    Font label1Font = this.$$$getFont$$$(null, -1, 24, label1.getFont());
    if (label1Font != null) label1.setFont(label1Font);
    label1.setForeground(new Color(-822419));
    label1.setText("Red: 9");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.insets = new Insets(0, 0, 30, 0);
    PlayPanel.add(label1, gbc);
    final JLabel label2 = new JLabel();
    Font label2Font = this.$$$getFont$$$(null, -1, 24, label2.getFont());
    if (label2Font != null) label2.setFont(label2Font);
    label2.setForeground(new Color(-9994047));
    label2.setText("Blue: 8");
    gbc = new GridBagConstraints();
    gbc.gridx = 5;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.EAST;
    gbc.insets = new Insets(0, 0, 30, 0);
    PlayPanel.add(label2, gbc);
    textField1 = new JTextField();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 6;
    gbc.gridwidth = 2;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(30, 0, 0, 0);
    PlayPanel.add(textField1, gbc);
    final JLabel label3 = new JLabel();
    label3.setText("# words:");
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 6;
    gbc.anchor = GridBagConstraints.EAST;
    gbc.insets = new Insets(30, 20, 0, 10);
    PlayPanel.add(label3, gbc);
    textField2 = new JTextField();
    gbc = new GridBagConstraints();
    gbc.gridx = 5;
    gbc.gridy = 6;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(30, 0, 0, 0);
    PlayPanel.add(textField2, gbc);
    submitButton = new JButton();
    submitButton.setText("Submit");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 7;
    gbc.gridwidth = 3;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(10, 0, 0, 0);
    PlayPanel.add(submitButton, gbc);
    final JLabel label4 = new JLabel();
    label4.setText("Give Hint:");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 6;
    gbc.anchor = GridBagConstraints.EAST;
    gbc.insets = new Insets(30, 0, 0, 10);
    PlayPanel.add(label4, gbc);
  }

  /**
   * @noinspection ALL
   */
  private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
    if (currentFont == null) return null;
    String resultName;
    if (fontName == null) {
      resultName = currentFont.getName();
    } else {
      Font testFont = new Font(fontName, Font.PLAIN, 10);
      if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
        resultName = fontName;
      } else {
        resultName = currentFont.getName();
      }
    }
    Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
    Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
    return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return PlayPanel;
  }

}
