package ui;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class Start {
  private JLabel title;
  private JTextField username;
  private JTextField gameid;
  private JButton joinExistingGameButton;
  private JButton newGameButton;
  private JLabel usernameLabel;
  private JLabel gameidLabel;
  private JPanel startPanel;


  public JPanel getPanel() {
    return startPanel;
  }

  public JButton getNewGameButton() {
    return newGameButton;
  }

  public JButton getJoinExistingGameButton() {
    return joinExistingGameButton;
  }

  public JTextField getUsername() {
    return username;
  }

  public JTextField getGameid() {
    return gameid;
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    startPanel = new JPanel();
    startPanel.setLayout(new GridBagLayout());
    title = new JLabel();
    Font titleFont = this.$$$getFont$$$(null, -1, 84, title.getFont());
    if (titleFont != null) title.setFont(titleFont);
    title.setText("Codenames");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    startPanel.add(title, gbc);
    usernameLabel = new JLabel();
    usernameLabel.setHorizontalAlignment(0);
    usernameLabel.setText("Username");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    startPanel.add(usernameLabel, gbc);
    username = new JTextField();
    username.setColumns(20);
    username.setVerifyInputWhenFocusTarget(true);
    username.setVisible(true);
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 3;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    startPanel.add(username, gbc);
    gameidLabel = new JLabel();
    gameidLabel.setText("Input Game ID if you are joining another game");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 4;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    startPanel.add(gameidLabel, gbc);
    gameid = new JTextField();
    gameid.setColumns(20);
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 5;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    startPanel.add(gameid, gbc);
    joinExistingGameButton = new JButton();
    joinExistingGameButton.setText("Join Existing Game");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 6;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    startPanel.add(joinExistingGameButton, gbc);
    newGameButton = new JButton();
    newGameButton.setText("New Game");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 7;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    startPanel.add(newGameButton, gbc);
  }

  /**
   * @noinspection ALL
   */
  private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
    if (currentFont == null) return null;
    String resultName;
    if (fontName == null) {
      resultName = currentFont.getName();
    } else {
      Font testFont = new Font(fontName, Font.PLAIN, 10);
      if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
        resultName = fontName;
      } else {
        resultName = currentFont.getName();
      }
    }
    Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
    Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
    return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return startPanel;
  }

}
